# Generated by Django 5.2.4 on 2025-07-15 10:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_note_no', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_no', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('value', models.CharField(max_length=255)),
                ('delivery_address', models.TextField()),
                ('size_cft', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_packages', models.CharField(max_length=255)),
                ('method_of_packing', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight_actual', models.FloatField()),
                ('weight_charges', models.FloatField()),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consignments.consignment')),
            ],
        ),
        migrations.CreateModel(
            name='ConsignmentItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('extra', models.FloatField()),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='consignments.consignment')),
            ],
        ),
        migrations.CreateModel(
            name='FreightCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight', models.FloatField()),
                ('advance', models.FloatField()),
                ('hamali', models.FloatField()),
                ('extra', models.FloatField()),
                ('st_charges', models.FloatField()),
                ('total', models.FloatField()),
                ('gst', models.FloatField()),
                ('consignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freight_charges', to='consignments.consignment')),
            ],
        ),
        migrations.CreateModel(
            name='TransportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=255)),
                ('driver_license_no', models.CharField(max_length=255)),
                ('driver_name', models.CharField(max_length=255)),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('e_way_bill_no', models.CharField(max_length=255)),
                ('consignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='consignments.consignment')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gst', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='consignment',
            name='consignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments_as_consignee', to='consignments.vendor'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='consignor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments_as_consignor', to='consignments.vendor'),
        ),
    ]
