# Generated by Django 5.2.4 on 2025-07-15 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freightcharges',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='freightcharges',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='freightcharges',
            name='hamali',
        ),
        migrations.AddField(
            model_name='consignment',
            name='person_liable_for_gst',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consignment',
            name='service_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='freightcharges',
            name='other_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportdetails',
            name='driver_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transportdetails',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignments_as_consignee', to='consignments.vendor'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='consignment_note_no',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='consignor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignments_as_consignor', to='consignments.vendor'),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='size_cft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='consignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consignments.consignment'),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='method_of_packing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='no_of_packages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='weight_actual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='weight_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitemsize',
            name='consignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='consignments.consignment'),
        ),
        migrations.AlterField(
            model_name='consignmentitemsize',
            name='extra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitemsize',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitemsize',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitemsize',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freightcharges',
            name='advance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freightcharges',
            name='consignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freight_charges', to='consignments.consignment'),
        ),
        migrations.AlterField(
            model_name='freightcharges',
            name='freight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freightcharges',
            name='st_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freightcharges',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetails',
            name='consignment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='consignments.consignment'),
        ),
        migrations.AlterField(
            model_name='transportdetails',
            name='driver_license_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetails',
            name='driver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetails',
            name='e_way_bill_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetails',
            name='from_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetails',
            name='to_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transportdetails',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LoadingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.TextField(blank=True, null=True)),
                ('in_date', models.TextField(blank=True, null=True)),
                ('out_time', models.TextField(blank=True, null=True)),
                ('out_date', models.TextField(blank=True, null=True)),
                ('consignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loading_point', to='consignments.consignment')),
            ],
        ),
        migrations.CreateModel(
            name='UnloadingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.TextField(blank=True, null=True)),
                ('in_date', models.TextField(blank=True, null=True)),
                ('out_time', models.TextField(blank=True, null=True)),
                ('out_date', models.TextField(blank=True, null=True)),
                ('consignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unloading_point', to='consignments.consignment')),
            ],
        ),
    ]
